heat_template_version: 2015-04-30

description: Simple template to deploy a all instances

resources:
  instance_1:
    type: OS::Nova::Server::K8sMaster
  instance_2:
    type: OS::Nova::Server::K8sSlave
  instance_3:
    type: OS::Nova::Server::MongoDB

outputs:
  k8s_master_ip:
    description: The IP address of the deployed instance
    value: { get_attr: [instance_1, first_address] }
  k8s_slave_ip:
    description: The IP address of the deployed instance
    value: { get_attr: [instance_2, first_address] }
  mongodb_ip:
    description: The IP address of the deployed instance
    value: { get_attr: [instance_3, first_address] }
