heat_template_version: 2015-04-30

description: Simple template to deploy the cws environement v1.0

parameters:
  public_net:
    type: string
    description: >
      ID or name of public network for which Elastic IP addresses will be allocated
  vpc_name:
    type: string
    description: Name of the VPC
  private_net_name:
    type: string
    description: Name of private network to be created
  private_subnet_name:
    type: string
    description: Name of private subnet to be created
  private_net_cidr:
    type: string
    description: Private network address (CIDR notation)
  private_net_gateway:
    type: string
    description: Private network gateway address
  private_net_pool_start:
    type: string
    description: Start of private network IP address allocation pool
  private_net_pool_end:
    type: string
    description: End of private network IP address allocation pool
  k8s_master_name:
    type: string
    default: k8s-master-00%index%
    description: Name of the K8S Master node.
  mongodb_name:
    type: string
    default: mongodb-00%index%
    description: Name of the mongodb node.
  glusterfs_name:
    type: string
    default: glusterfs-00%index%
    description: Name of the glusterfs node.
  etcd_name:
    type: string
    default: etcd-00%index%
    description: Name of the etcd node.
  k8s_master_volume_name:
    type: string
    default: vol-k8sm-00%index%
    description: Name of the K8S Master Volume.
  mongodb_volume_name:
    type: string
    default: vol-mgdb-00%index%
    description: Name of the Mongodb Volume.
  glusterfs_volume_name:
    type: string
    default: vol-glfs-00%index%
    description: Name of the Glusterfs Volume.
  etcd_volume_name:
    type: string
    default: vol-etcd-00%index%
    description: Name of the Etcd Volume.
    
resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_net_name }

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: { get_param: private_subnet_name }
      network_id: { get_resource: private_net }
      cidr: { get_param: private_net_cidr }
      gateway_ip: { get_param: private_net_gateway }
      allocation_pools:
        - start: { get_param: private_net_pool_start }
          end: { get_param: private_net_pool_end }

  router:
    type: OS::Neutron::Router
    properties:
      name: { get_param: vpc_name }
      external_gateway_info:
        network: { get_param: public_net }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet }

  resource_group_K8sMaster:
    type: OS::Heat::ResourceGroup
    depends_on: private_subnet
    properties:
      count: 3
      resource_def:
        type: OS::Nova::Server::K8sMaster
        properties:
          k8s_master_name: { get_param: k8s_master_name }
          k8s_master_volume_name: { get_param: k8s_master_volume_name }

  scaleup_group_K8sSlave:
    type: OS::Heat::AutoScalingGroup
    depends_on: private_subnet
    properties:
      cooldown: 60
      desired_capacity: 5
      max_size: 15
      min_size: 3
      resource:
        type: OS::Nova::Server::K8sSlave

  resource_group_MongoDB:
    type: OS::Heat::ResourceGroup
    depends_on: private_subnet
    properties:
      count: 3
      resource_def:
        type: OS::Nova::Server::MongoDB
        properties:
          mongodb_name: { get_param: mongodb_name }
          mongodb_volume_name: { get_param: mongodb_volume_name }

  resource_group_GlusterFS:
    type: OS::Heat::ResourceGroup
    depends_on: private_subnet
    properties:
      count: 2
      resource_def:
        type: OS::Nova::Server::GlusterFS
        properties:
          glusterfs_name: { get_param: glusterfs_name }
          glusterfs_volume_name: { get_param: glusterfs_volume_name }
          
  resource_group_Etcd:
    type: OS::Heat::ResourceGroup
    depends_on: private_subnet
    properties:
      count: 3
      resource_def:
        type: OS::Nova::Server::Etcd
        properties:
          etcd_name: { get_param: etcd_name }
          etcd_volume_name: { get_param: etcd_volume_name }
          
