heat_template_version: 2015-04-30

description: Template to deploy the CWS environement v1.0

parameters:
  public_net:
    type: string
    description: >
      ID or name of public network for which Elastic IP addresses will be allocated
  dns_servers:
    type: comma_delimited_list
    default: ['100.125.4.25','8.8.8.8']
    description: Comma separated list of DNS nameservers for the private network.
  vpc_name:
    type: string
    default: cws-vpc
    description: Name of the VPC
  dns_domain_name:
    type: string
    default: cws.environement.
    description: Name of the DNS Domain
  private_net_name:
    type: string
    default: cws-network
    description: Name of private network to be created
  private_subnet_name:
    type: string
    default: cws-subnet
    description: Name of private subnet to be created
  private_net_cidr:
    type: string
    default: 172.16.0.0/16
    description: Private network address (CIDR notation)
  private_net_gateway:
    type: string
    default: 172.16.0.1
    description: Private network gateway address
  private_net_pool_start:
    type: string
    default: 172.16.0.100
    description: Start of private network IP address allocation pool
  private_net_pool_end:
    type: string
    default: 172.16.0.200
    description: End of private network IP address allocation pool
  k8s_master_name:
    type: string
    default: k8s-master-00%index%
    description: Name of the K8S Master node.
  mongodb_name:
    type: string
    default: mongodb-00%index%
    description: Name of the mongodb node.
  glusterfs_name:
    type: string
    default: glusterfs-00%index%
    description: Name of the glusterfs node.
  etcd_name:
    type: string
    default: etcd-00%index%
    description: Name of the etcd node.
  k8s_master_volume_name:
    type: string
    default: vol-k8sm-00%index%
    description: Name of the K8S Master Volume.
  mongodb_volume_name:
    type: string
    default: vol-mgdb-00%index%
    description: Name of the Mongodb Volume.
  glusterfs_volume_name:
    type: string
    default: vol-glfs-00%index%
    description: Name of the Glusterfs Volume.
  etcd_volume_name:
    type: string
    default: vol-etcd-00%index%
    description: Name of the Etcd Volume.
  common_secgroup_name:
    type: string
    default: cws-common-secgrp
    description: Name of the Common Security group.
  jumpbox_secgroup_name:
    type: string
    default: cws-jmbx-secgrp
    description: Name of the JumpBox Security group.
  k8ss_secgroup_name:
    type: string
    default: cws-k8ss-secgrp
    description: Name of the K8S Slaves Security group.
    
resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_net_name }

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: { get_param: private_subnet_name }
      network_id: { get_resource: private_net }
      cidr: { get_param: private_net_cidr }
      gateway_ip: { get_param: private_net_gateway }
      dns_nameservers: { get_param: dns_servers }
      allocation_pools:
        - start: { get_param: private_net_pool_start }
          end: { get_param: private_net_pool_end }

  router:
    type: OS::Neutron::Router
    properties:
      name: { get_param: vpc_name }
      external_gateway_info:
        network: { get_param: public_net }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet }

  common_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name:  { get_param: common_secgroup_name }
      description: Ping
      rules:
      - protocol: icmp
        remote_ip_prefix: 0.0.0.0/0

  k8ss_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name: { get_param: k8ss_secgroup_name }
      description: HTTPS and HTTP
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 443
          port_range_max: 443

  jumpbox_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name:  { get_param: jumpbox_secgroup_name }
      description: SSH
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22
          
  resource_group_K8sMaster:
    type: OS::Heat::ResourceGroup
    depends_on: router_interface
    properties:
      count: 3
      resource_def:
        type: OS::Nova::Server::K8sMaster
        properties:
          k8s_master_name: { get_param: k8s_master_name }
          k8s_master_volume_name: { get_param: k8s_master_volume_name }
          common_secgroup: { get_resource: common_secgroup }
          
  autoscaled_group_K8sSlave:
    type: OS::Heat::AutoScalingGroup
    depends_on: router_interface
    properties:
      cooldown: 60
      desired_capacity: 5
      max_size: 15
      min_size: 3
      resource:
        type: OS::Nova::Server::K8sSlave
        properties:
          common_secgroup: { get_resource: common_secgroup }
          k8ss_secgroup: { get_resource: k8ss_secgroup }

  resource_group_MongoDB:
    type: OS::Heat::ResourceGroup
    depends_on: router_interface
    properties:
      count: 3
      resource_def:
        type: OS::Nova::Server::MongoDB
        properties:
          mongodb_name: { get_param: mongodb_name }
          mongodb_volume_name: { get_param: mongodb_volume_name }
          common_secgroup: { get_resource: common_secgroup }
          
  resource_group_GlusterFS:
    type: OS::Heat::ResourceGroup
    depends_on: router_interface
    properties:
      count: 2
      resource_def:
        type: OS::Nova::Server::GlusterFS
        properties:
          glusterfs_name: { get_param: glusterfs_name }
          glusterfs_volume_name: { get_param: glusterfs_volume_name }
          common_secgroup: { get_resource: common_secgroup }
          
  resource_group_Etcd:
    type: OS::Heat::ResourceGroup
    depends_on: router_interface
    properties:
      count: 3
      resource_def:
        type: OS::Nova::Server::Etcd
        properties:
          etcd_name: { get_param: etcd_name }
          etcd_volume_name: { get_param: etcd_volume_name }
          common_secgroup: { get_resource: common_secgroup }

outputs:
  K8sMaster_nodes_info:
    description: Hostname and IP adresses of the Kubernetes master nodes
    value: { get_attr: [ resource_group_K8sMaster, k8sm_instance_info ] }
  K8sSlave_nodes_info:
    description: Hostname and Ip adresses of the Kubernetes slave nodes
    value: { get_attr: [ autoscaled_group_K8sSlave, outputs_list, k8ss_instance_info ] }
  Autoscaled_group_K8sSlave_size:
    description: This is the current size of the auto scaling group.
    value: { get_attr: [ autoscaled_group_K8sSlave, current_size ] }
  GlusterFS_nodes_info:
    description: Hostname and Ip adresses of the GlusterFS nodes
    value: { get_attr: [ resource_group_GlusterFS, glfs_instance_info ] }
  MongoDB_nodes_info:
    description: Hostname and Ip adresses of the MongoDB nodes
    value: { get_attr: [ resource_group_MongoDB, mgdb_instance_info ] }
  Etcd_nodes_info:
    description: Hostname and Ip adresses of the Etcd nodes
    value: { get_attr: [ resource_group_Etcd, etcd_instance_info ] }
