heat_template_version: 2015-04-30

description: Simple template to deploy a all instances

parameters:
  public_net:
    type: string
    description: >
      ID or name of public network for which floating IP addresses will be allocated
  private_net_name:
    type: string
    description: Name of private network to be created
  private_net_cidr:
    type: string
    description: Private network address (CIDR notation)
  private_net_gateway:
    type: string
    description: Private network gateway address
  private_net_pool_start:
    type: string
    description: Start of private network IP address allocation pool
  private_net_pool_end:
    type: string
    description: End of private network IP address allocation pool

resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_net_name }

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: { get_param: private_net_cidr }
      gateway_ip: { get_param: private_net_gateway }
      allocation_pools:
        - start: { get_param: private_net_pool_start }
          end: { get_param: private_net_pool_end }

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet }

  scaleup_group_K8sMaster:
    type: OS::Heat::ResourceGroup
    depends_on: private_subnet
    properties:
      count: 3
      name: master_%index%
      resource_def:
        type: OS::Nova::Server::K8sMaster

  scaleup_group_K8sSlave:
    type: OS::Heat::AutoScalingGroup
    depends_on: private_subnet
    properties:
      cooldown: 60
      desired_capacity: 3
      max_size: 15
      min_size: 3
      resource:
        type: OS::Nova::Server::K8sSlave

  scaleup_group_MongoDB:
    type: OS::Heat::ResourceGroup
    depends_on: private_subnet
    properties:
      count: 3
      resource_def:
        type: OS::Nova::Server::MongoDB

  scaleup_group_GlusterFS:
    type: OS::Heat::ResourceGroup
    depends_on: private_subnet
    properties:
      count: 2
      resource_def:
        type: OS::Nova::Server::GlusterFS

  scaleup_group_Etcd:
    type: OS::Heat::ResourceGroup
    depends_on: private_subnet
    properties:
      count: 3
      resource_def:
        type: OS::Nova::Server::Etcd
